### PR TITLE
Issue #7:Change Background Image of Shows Page

### PR DESCRIPTION
**Pull request by Wolfy7**
Added a different Background image for Shows Page as described.

Fix https://github.com/akk312000/Movie-Recommender/issues/7

### CODE REVIEW

**Review by akk312000 — CHANGES_REQUESTED** [review]
Hey @Wolfy7 , Thanks for the PR, everything looks good but the background image isn't repeating now on search results page as it used to.
image
Can you please fix that as well?

**Comment by Wolfy7** [comment]
@akk312000 sure, of course. Will fix this later

**Comment by Wolfy7** [comment]
Had some issues with the html/css solution, so reverted them.
Now the background image gets changed via javacript for Shows/showSearch.

Please, have a look if this solution is still okay.

**Review by akk312000 — APPROVED** [review]
Cool, everything is working now and the changes you made now look perfect. Thanks for the PR @Wolfy7 .

**Pull request merged**
